import{S as h}from"./assets/vendor-10cb7c31.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const a="/goit-js-hw-11/assets/icons-f810c139.svg",g="https://pixabay.com/api/",m="",d=o=>new Promise((n,s)=>fetch(o).then(r=>(r.ok||s(new Error(`HTTP error, status: ${r.status}`)),r.json())).then(r=>n(r)).catch(r=>s(r)));function p(o){const n={key:m,q:encodeURIComponent(o),image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:20},s=`${g}?${new URLSearchParams(n).toString()}`;return new Promise((r,e)=>{d(s).then(t=>{t.hits.length||e("Sorry, there are no images matching your search query. Please, try again!"),r(t.hits)}).catch(t=>{e(`Error fetching images: ${t.message}`)})})}const y="#ffffff",b="#f5f5f5",c=document.querySelector(".gallery"),l=document.querySelector(".loader"),u=document.querySelector(".search-form");u.addEventListener("submit",v);let f=new h(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,nav:!0,navText:[`<svg class="lightbox-button-icon-prev" width="24" height="24" aria-label="icon arrow left">
          <use href="${a}#icon-chevron-left"></use>
        </svg>`,`<svg class="lightbox-button-icon-next" width="24" height="24" aria-label="icon arrow right">
          <use href="${a}#icon-chevron-right"></use>
        </svg>`],close:!0,closeText:`
        <svg class="lightbox-close-icon" width="16" height="16">
          <use href="${a}#close-form"></use>
        </svg>`,enableKeyboard:!0,showCounter:!0,animationSlide:!0,loop:!0});function v(o){o.preventDefault(),l.style.display="block";const n=o.currentTarget.search.value.trim();p(n).then(s=>S(s)).catch(s=>w(s))}function w(o){u.search.value="",l.style.display="none",L(o),c.style.backgroundColor=b,c.innerHTML="",f.refresh()}function S(o){u.search.value="",l.style.display="none",c.style.backgroundColor=y,createCardsGallery(o,c),f.refresh()}function L(o){iziToast.show({message:o,messageColor:"#fafafb",messageSize:"16px",backgroundColor:"#fc5a5a",position:"topRight",closeOnEscape:!0,close:!0,icon:"Icomoon",iconUrl:`${iconXUrl}`,iconColor:"#fafafb"})}
//# sourceMappingURL=commonHelpers.js.map
